// Auto-generated by scripts/gen-version.ts - do not edit
export const BUILD_VERSION = {
  gitHash: '5a24c7ea01d54b4c7c0f56a6c7fcb994c5344265',
  gitHashShort: '5a24c7e-dirty',
  buildTime: '2026-03-10T14:40:51.916Z',
  dirty: true,
}
