// Auto-generated by scripts/gen-version.ts - do not edit
export const BUILD_VERSION = {
  gitHash: 'a890abd30d9c4662534012fbc40c3d81fdb7e409',
  gitHashShort: 'a890abd-dirty',
  buildTime: '2026-03-11T04:59:38.780Z',
  dirty: true,
}
