// Auto-generated by scripts/gen-version.ts - do not edit
export const BUILD_VERSION = {
  gitHash: 'aea004fa9c88e6e2d0b526e29e9935dc46d53e30',
  gitHashShort: 'aea004f-dirty',
  buildTime: '2026-03-10T14:52:45.356Z',
  dirty: true,
}
