#!/usr/bin/env bun
/**
 * Generate src/shared/version.ts with git hash and build time.
 * Run before compiling binaries. Falls back gracefully when git is unavailable (e.g. Docker).
 */
import { execSync } from 'node:child_process'
import { join } from 'node:path'

const ROOT = join(import.meta.dir, '..')
const OUT = join(ROOT, 'src', 'shared', 'version.ts')

let gitHash = 'unknown'
let dirty = false
try {
  gitHash = execSync('git rev-parse HEAD', { cwd: ROOT, stdio: ['pipe', 'pipe', 'pipe'] })
    .toString()
    .trim()
  dirty =
    execSync('git status --porcelain', { cwd: ROOT, stdio: ['pipe', 'pipe', 'pipe'] })
      .toString()
      .trim().length > 0
} catch {
  // No git available (Docker build, CI, etc.)
}

const gitHashShort = gitHash === 'unknown' ? 'unknown' : gitHash.slice(0, 7)
const buildTime = new Date().toISOString()

let recentCommits: Array<{ hash: string; message: string }> = []
try {
  const log = execSync('git log --oneline -3', { cwd: ROOT, stdio: ['pipe', 'pipe', 'pipe'] })
    .toString()
    .trim()
  recentCommits = log.split('\n').map(line => {
    const spaceIdx = line.indexOf(' ')
    return { hash: line.slice(0, spaceIdx), message: line.slice(spaceIdx + 1) }
  })
} catch {
  // No git
}

const content = `// Auto-generated by scripts/gen-version.ts - do not edit
export const BUILD_VERSION = {
  gitHash: '${gitHash}',
  gitHashShort: '${gitHashShort}${dirty ? '-dirty' : ''}',
  buildTime: '${buildTime}',
  dirty: ${dirty},
  recentCommits: ${JSON.stringify(recentCommits)},
}
`

await Bun.write(OUT, content)
console.log(`[version] ${gitHashShort}${dirty ? '-dirty' : ''} @ ${buildTime}`)
